language: php

sudo: false

matrix:
  include:
    - php: "7.1.28"
      env: COMPOSER_PSR7="slim/psr7"
    - php: "7.1.28"
      env: COMPOSER_PSR7="nyholm/psr7 nyholm/psr7-server"
    - php: "7.1.28"
      env: COMPOSER_PSR7="guzzlehttp/psr7 http-interop/http-factory-guzzle"
    - php: "7.1.28"
      env: COMPOSER_PSR7="zendframework/zend-diactoros"

before_install:
  - sudo apt-get update > /dev/null

install:
  - travis_retry composer update --prefer-dist --no-interaction
  - travis_retry composer require $COMPOSER_PSR7

before_script:
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
  - sudo chown -R travis:travis /var/lib/apache2/fastcgi
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/000-default.conf
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
  - sudo service apache2 restart

script:
  - php tests/test.php
